name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: npm install -g yarn
      - run: yarn
      - run: yarn lint
      - run: yarn build
        env:
          CI: true
