name: Release

# Not ready for this

on:
  # since pushing to main / staging branch is disabled, the only push should come from a pull request
  push:
    branches: [main]
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install dependencies
        run: yarn
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
        run: npx semantic-release
